export const businessName = [
  "Percepta (security)",
  "Exela Movers",
  "Ibotta, Inc. (consumer services)",
  "Wanderu (hospitality & tourism)",
  "Aceable, Inc. (online learning)",
  "Intrepid Travel",
  "Defendify (security)",
  "Twisters Gymnastics Academy",
  "Aims Community College",
  "Kaboom Fireworks",
  "Compass Mortgage",
  "Marathon Physical Therapy",
  "Semicolon Bookstore",
  "9Yards Media",
  "When Pigs Fly (food)",
  "Light As a Feather (health and beauty)",
  "More Than Words (retail)",
  "Top It Off (fashion)",
  "Bent Out of Shape Jewelry",
  "To Each Their Own, LLC (beauty salon)",
  "Like You Mean It Productions",
  "What You Will Yoga",
  "EBA’s (Everything But Anchovies)",
  "Soft As a Grape (clothing and retail)",
  "Groupon",
  "Influitive",
  "Spinfluence",
  "Intellivision",
  "Perficient (proficient, perfect, efficient)",
  "Omnilert",
  "Technologent",
  "Securiteam",
  "Innometrics",
  "Puzzle Huddle",
  "7Eleven",
  "Hobby Lobby",
  "The Knickknack Shack",
  "Los Amigos Taqueria",
  "Plan4Demand",
  "Chic Boutique Consignments",
  "ElemenOPillows",
  "Clickety Clack (game store)",
  "Horizons for Homeless Children",
  "Superscapes",
  "The Tiny Tassel",
  "Mighty Mule (security)",
  "Decorating Den Interiors",
  "Encore Electric, Inc.",
  "Beet Box Cafe",
  "Arctic Wolf Neworks, Inc (cyber security)",
  "The Zebra (car insurance comparison website)",
  "Purple Mango (this is the name for a cafe, a skincare and laser office, and a media company)",
  "Blue Kite Web Solutions LLC",
  "The Maroon Door (restaurant)",
  "Unchained Carrot (marketing)",
  "The Orange Goat (restaurant)",
  "Thump Coffee",
  "Clink Boston (a bar)",
  "Clink Inc",
  "Crunch and Munch (also rhymes!)",
  "Crunch Fitness (not used as onomatopoeia, but still a fun word!)",
  "Whoosh Auto Care",
  "Beep Beep Auto School",
  "Whizz Kids Tutoring",
  "The Breelancers (brie/cheese store)",
  "Weed Man Lawn Care",
  "Real Imposters Jewelry",
  "Kerplunk Portables",
  "The Codfather",
  "Indiana Bones and the Temple of Groom",
  "PrimaCARE (medical)",
  "Kindness Animal Hospital",
  "Patient First Chiropractic & Physical Therapy",
  "Fidelity Investments",
  "Tenacity (education)",
  "Bottom Line Tax Services",
  "B2B Salesify",
  "Anytime Fitness (24-hour gym)",
  "Holistic Business Excellence",
  "One Stop Painting & Renovating",
  "CustomMade (jewelry)",
  "EZ Eyecare",
  "Reliant At Home",
  "EveryStep (home care)",
  "5280 Digital (5280 feet in a mile)",
  "Siteimprove (websites)",
  "Forecast5 Analytics",
  "Five Star Senior Living",
  "The Moving Guys",
  "Sister’s Restaurant",
  "Ruggiero Brothers Oil",
  "Angela’s Bridal",
  "The Tree Fellas",
  "The Coffee Girl",
  "The Building People, LLC",
  "The Wine Guys",
  "Amigos Barber Shop",
  "Tatte Bakery",
  "Tatte means grandma in Hebrew.",
  "Zio’s Deli",
  "Zio means uncle in Italian.",
  "Aegis Chiropractic & Physical Therapy",
  "Tiny Rebellion",
  "Small Giants",
  "Think Big Work Small",
  "Small Ax Creative",
  "Small Potatoes Catering",
  "Small Dog Creative",
  "Tiny Legend Learning Academy",
  "Local Bounti",
  "Local Roots",
  "Neighborly Software",
  "Neighbors Construction",
  "Nearby Notary LLC",
  "Local 149",
  "Growthonics",
  "ClatterChatter",
  "Fewofmany",
  "Volume Nine",
  "Ignite Visibility",
  "The Bureau of Small Projects",
  "Idea Grove",
  "KickStart Marketing",
  "Digital Dive Marketing",
  "She Runs It",
  "Be Busy Being Awesome Agency",
  "SmarkLabs",
  "The Growth Co.",
  "Creative Juice",
  "Be Seen Solutions",
  "Color 9 Creative",
  "The Invisible Paintbrush",
  "Obvious Agency",
  "Brandopedia",
  "Fill the Gap Marketing Limited",
  "Empiric Marketing",
];
